# Generated by Django 4.2.14 on 2024-07-31 10:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookalesson", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bookings",
            new_name="Booking",
        ),
        migrations.RenameModel(
            old_name="LessonType",
            new_name="Lesson",
        ),
    ]
