# Generated by Django 4.2.14 on 2024-07-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookalesson", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessontype",
            name="excerpt",
            field=models.TextField(blank=True),
        ),
    ]
