# Generated by Django 4.2.14 on 2024-07-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookalesson", "0002_lessontype_excerpt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lessontype",
            old_name="level",
            new_name="lesson_choices",
        ),
        migrations.AddField(
            model_name="instructor",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
