# Generated by Django 4.2.14 on 2024-07-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookalesson", "0003_rename_level_lessontype_lesson_choices_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
