# Generated by Django 4.2.14 on 2024-08-01 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookalesson",
            "0003_remove_commentonlesson_unique_user_lesson_comment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lessondate",
            name="lesson",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_dates",
                to="bookalesson.lesson",
            ),
            preserve_default=False,
        ),
    ]
