# Generated by Django 4.2.14 on 2024-08-01 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookalesson", "0004_lessondate_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessondate",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_dates_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
