# Generated by Django 4.2.14 on 2024-07-25 21:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookalesson", "0006_commentonlesson_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BookingDate",
            new_name="Bookings",
        ),
    ]
