# Generated by Django 4.2.14 on 2024-08-01 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookalesson", "0006_alter_lessondate_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessondate",
            name="user",
        ),
    ]
