# Generated by Django 4.2.14 on 2024-07-25 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookalesson", "0007_rename_bookingdate_bookings"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LessonType",
            new_name="Lessons",
        ),
    ]
