# Generated by Django 4.2.14 on 2024-08-02 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookalesson", "0009_remove_lessondate_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessondate",
            name="user",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booked_lesson_dates",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
