# Generated by Django 4.2.14 on 2024-07-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="content",
            field=models.TextField(default="Default content"),
        ),
    ]
